-- database.sql
CREATE DATABASE IF NOT EXISTS insighted;
USE insighted;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS syllabuses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    course_title VARCHAR(255) NOT NULL,
    structure JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
USE insighted;

-- ==============================================================================
-- 1. CAREER & DUAL TRACK ROADMAP (Features 3 & 7)
-- ==============================================================================

-- Notes: Stores the student's target role to allow the Gemini API to perform 
-- gap analysis against the uploaded syllabus.
CREATE TABLE IF NOT EXISTS career_goals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE, 
    target_role VARCHAR(100) NOT NULL, 
    target_company_tier VARCHAR(50), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Notes: Stores the "Interview High" topics generated by Gemini that are missing 
-- from the university syllabus.
CREATE TABLE IF NOT EXISTS roadmap_recommendations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    topic_name VARCHAR(100) NOT NULL, 
    category VARCHAR(50), 
    importance_level ENUM('Critical', 'High', 'Medium') DEFAULT 'High',
    is_completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ==============================================================================
-- 2. AI QUIZ ENGINE (Feature 1)
-- ==============================================================================

-- Notes: Holds the exact JSON array of questions, options, and explanations 
-- returned by Gemini, linked directly to your existing syllabuses table.
CREATE TABLE IF NOT EXISTS quizzes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    syllabus_id INT NOT NULL,
    topic_name VARCHAR(100) NOT NULL,
    questions_data JSON NOT NULL,
    score INT DEFAULT 0, 
    status ENUM('pending', 'completed') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (syllabus_id) REFERENCES syllabuses(id) ON DELETE CASCADE
);

-- ==============================================================================
-- 3. TASK MANAGEMENT & GOAL ANALYTICS (Features 4 & 5)
-- ==============================================================================

-- Notes: This table powers the Dynamic Next Task engine. It stores deadlines 
-- and estimated times to calculate completion velocity.
CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    deadline DATETIME NOT NULL,
    estimated_minutes INT NOT NULL,
    actual_minutes INT NULL, 
    importance_level INT DEFAULT 3, 
    is_industry_track BOOLEAN DEFAULT FALSE, 
    status ENUM('pending', 'in_progress', 'completed') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ==============================================================================
-- 4. HABIT TRACKING & AI INSIGHTS (Features 2, 3 & 6)
-- ==============================================================================

-- Notes: Logs the raw start/end times required for the DBSCAN clustering algorithm 
-- to identify peak flow states.
CREATE TABLE IF NOT EXISTS study_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    subject_name VARCHAR(100) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    duration_minutes INT NOT NULL,
    focus_score INT NOT NULL CHECK (focus_score BETWEEN 0 AND 100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Notes: Stores the weekly aggregations and the Gemini-generated narrative report 
-- to serve the dashboard without making redundant API calls.
CREATE TABLE IF NOT EXISTS weekly_insights (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    week_start_date DATE NOT NULL,
    week_end_date DATE NOT NULL,
    insight_text TEXT NOT NULL,
    stats_json JSON NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ==============================================================================
-- 5. PERFORMANCE INDEXES
-- ==============================================================================
-- Notes: Essential for ensuring fast queries on foreign keys and date ranges 
-- as the tables grow with user activity.

CREATE INDEX idx_tasks_user_status ON tasks(user_id, status);
CREATE INDEX idx_tasks_deadline ON tasks(deadline);
CREATE INDEX idx_sessions_user_time ON study_sessions(user_id, start_time);
CREATE INDEX idx_quizzes_user_syllabus ON quizzes(user_id, syllabus_id);