import React, { useState } from 'react';
import { CheckCircle, XCircle, ArrowRight, RotateCcw, Award } from 'lucide-react';
import styles from './Assessment.module.css';

const Assessment = () => {
  // MOCK DATA: Generated by AI RAG Model
  const questions = [
    {
      id: 1,
      question: "What is the time complexity of searching in a balanced Binary Search Tree?",
      options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
      correct: 1 // Index of correct answer
    },
    {
      id: 2,
      question: "Which normal form removes transitive dependency?",
      options: ["1NF", "2NF", "3NF", "BCNF"],
      correct: 2
    },
    {
      id: 3,
      question: "In React, which hook is used to handle side effects?",
      options: ["useState", "useReducer", "useEffect", "useMemo"],
      correct: 2
    }
  ];

  const [currentQ, setCurrentQ] = useState(0);
  const [selectedOption, setSelectedOption] = useState(null);
  const [score, setScore] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [isAnswered, setIsAnswered] = useState(false);

  const handleOptionClick = (index) => {
    if (isAnswered) return;
    setSelectedOption(index);
    setIsAnswered(true);

    if (index === questions[currentQ].correct) {
      setScore(score + 1);
    }
  };

  const handleNext = () => {
    if (currentQ < questions.length - 1) {
      setCurrentQ(currentQ + 1);
      setSelectedOption(null);
      setIsAnswered(false);
    } else {
      setShowResult(true);
    }
  };

  const resetQuiz = () => {
    setCurrentQ(0);
    setSelectedOption(null);
    setScore(0);
    setShowResult(false);
    setIsAnswered(false);
  };

  // --- RENDER RESULT SCREEN ---
  if (showResult) {
    return (
      <div className={styles.resultContainer}>
        <Award size={64} className={styles.awardIcon} />
        <h1>Quiz Completed!</h1>
        <p className={styles.scoreText}>You scored <strong>{score} / {questions.length}</strong></p>
        
        <div className={styles.actionButtons}>
          <button className={styles.retryBtn} onClick={resetQuiz}>
            <RotateCcw size={18} /> Retry Quiz
          </button>
        </div>
      </div>
    );
  }

  // --- RENDER QUESTION SCREEN ---
  return (
    <div className={styles.assessmentContainer}>
      
      {/* HEADER */}
      <header className={styles.header}>
        <div>
          <span className={styles.badge}>AI Generated Assessment</span>
          <h2>Data Structures & Algorithms</h2>
        </div>
        <div className={styles.timer}>14:35</div>
      </header>

      {/* PROGRESS BAR */}
      <div className={styles.progressContainer}>
        <div 
          className={styles.progressBar} 
          style={{ width: `${((currentQ + 1) / questions.length) * 100}%` }}
        ></div>
      </div>

      {/* QUESTION CARD */}
      <main className={styles.questionCard}>
        <span className={styles.questionCount}>Question {currentQ + 1} of {questions.length}</span>
        <h3 className={styles.questionText}>{questions[currentQ].question}</h3>

        <div className={styles.optionsGrid}>
          {questions[currentQ].options.map((option, index) => {
            // Determine styling based on state
            let optionClass = styles.optionBtn;
            if (isAnswered) {
              if (index === questions[currentQ].correct) optionClass += ` ${styles.correct}`;
              else if (index === selectedOption) optionClass += ` ${styles.wrong}`;
            }

            return (
              <button 
                key={index} 
                className={optionClass} 
                onClick={() => handleOptionClick(index)}
                disabled={isAnswered}
              >
                <div className={styles.optionMarker}>
                   {isAnswered && index === questions[currentQ].correct ? <CheckCircle size={18} /> : 
                    isAnswered && index === selectedOption ? <XCircle size={18} /> : 
                    String.fromCharCode(65 + index)} 
                </div>
                {option}
              </button>
            );
          })}
        </div>

        {/* NEXT BUTTON */}
        <div className={styles.footer}>
          <button 
            className={styles.nextBtn} 
            onClick={handleNext}
            disabled={!isAnswered}
          >
            {currentQ === questions.length - 1 ? 'Finish Quiz' : 'Next Question'} 
            <ArrowRight size={18} />
          </button>
        </div>
      </main>

    </div>
  );
};

export default Assessment;